using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace TupleClient.Generators;

[Generator]
public class RemoteEvalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all methods with [RemoteEval] attribute
        var methodDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidateMethod(s),
                transform: static (ctx, _) => GetMethodInfo(ctx))
            .Where(static m => m is not null);

        // Combine with compilation
        var compilationAndMethods = context.CompilationProvider.Combine(methodDeclarations.Collect());

        // Generate source
        context.RegisterSourceOutput(compilationAndMethods,
            static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsCandidateMethod(SyntaxNode node)
    {
        return node is MethodDeclarationSyntax method &&
               method.AttributeLists.Count > 0;
    }

    private static MethodInfo? GetMethodInfo(GeneratorSyntaxContext context)
    {
        var methodSyntax = (MethodDeclarationSyntax)context.Node;

        // Check if it has the RemoteEval attribute
        foreach (var attributeList in methodSyntax.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                var name = attribute.Name.ToString();
                if (name == "RemoteEval" || name == "RemoteEvalAttribute" ||
                    name == "TupleClient.RemoteEval" || name == "TupleClient.RemoteEvalAttribute")
                {
                    // Get the containing class/type
                    var containingType = methodSyntax.Parent as TypeDeclarationSyntax;
                    if (containingType == null) return null;

                    // Get namespace
                    var namespaceDecl = containingType.Parent as BaseNamespaceDeclarationSyntax;
                    var namespaceName = namespaceDecl?.Name.ToString() ?? "";

                    // Extract the method body
                    var body = methodSyntax.Body;
                    if (body == null) return null;

                    // Get the body text without the braces
                    var bodyText = body.Statements.ToFullString();

                    return new MethodInfo(
                        namespaceName,
                        containingType.Identifier.Text,
                        methodSyntax.Identifier.Text,
                        bodyText.Trim());
                }
            }
        }

        return null;
    }

    private static void Execute(Compilation compilation, ImmutableArray<MethodInfo?> methods, SourceProductionContext context)
    {
        if (methods.IsDefaultOrEmpty)
            return;

        var validMethods = methods.Where(m => m is not null).Cast<MethodInfo>().ToList();
        if (validMethods.Count == 0)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace TupleClient;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Contains the extracted code strings from methods marked with [RemoteEval].");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class RemoteCode");
        sb.AppendLine("{");

        foreach (var method in validMethods)
        {
            var propertyName = method.MethodName;
            var escapedCode = EscapeForVerbatimString(method.BodyText);

            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Code extracted from {method.ContainingType}.{method.MethodName}");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public static string {propertyName} => @\"{escapedCode}\";");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        context.AddSource("RemoteCode.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string EscapeForVerbatimString(string text)
    {
        // In verbatim strings, only double quotes need to be escaped (by doubling them)
        return text.Replace("\"", "\"\"");
    }

    private class MethodInfo
    {
        public string Namespace { get; }
        public string ContainingType { get; }
        public string MethodName { get; }
        public string BodyText { get; }

        public MethodInfo(string ns, string containingType, string methodName, string bodyText)
        {
            Namespace = ns;
            ContainingType = containingType;
            MethodName = methodName;
            BodyText = bodyText;
        }
    }
}
